# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Api.FunctionsAttributeMappingFunctionSchema do
  @moduledoc """
  API calls for all endpoints tagged `FunctionsAttributeMappingFunctionSchema`.
  """

  alias MicrosoftGraph.Connection
  import MicrosoftGraph.RequestBuilder

  @doc """
  Add new entity to functions

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `microsoft_graph_attribute_mapping_function_schema` (MicrosoftGraphAttributeMappingFunctionSchema): New entity
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_attribute_mapping_function_schema_create_attribute_mapping_function_schema(Tesla.Env.client, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t, keyword()) :: {:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_attribute_mapping_function_schema_create_attribute_mapping_function_schema(connection, microsoft_graph_attribute_mapping_function_schema, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/functions")
      |> add_param(:body, :body, microsoft_graph_attribute_mapping_function_schema)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {"2XX", MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end

  @doc """
  Delete entity from functions

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `attribute_mapping_function_schema_id` (String.t): The unique identifier of attributeMappingFunctionSchema
  - `opts` (keyword): Optional parameters
    - `:"If-Match"` (String.t): ETag

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_attribute_mapping_function_schema_delete_attribute_mapping_function_schema(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_attribute_mapping_function_schema_delete_attribute_mapping_function_schema(connection, attribute_mapping_function_schema_id, opts \\ []) do
    optional_params = %{
      :"If-Match" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/functions/#{attribute_mapping_function_schema_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end

  @doc """
  Get entity from functions by key

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `attribute_mapping_function_schema_id` (String.t): The unique identifier of attributeMappingFunctionSchema
  - `opts` (keyword): Optional parameters
    - `:"$select"` ([String.t]): Select properties to be returned
    - `:"$expand"` ([String.t]): Expand related entities

  ### Returns

  - `{:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_attribute_mapping_function_schema_get_attribute_mapping_function_schema(Tesla.Env.client, String.t, keyword()) :: {:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_attribute_mapping_function_schema_get_attribute_mapping_function_schema(connection, attribute_mapping_function_schema_id, opts \\ []) do
    optional_params = %{
      :"$select" => :query,
      :"$expand" => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/functions/#{attribute_mapping_function_schema_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {"2XX", MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end

  @doc """
  Get entities from functions

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"$top"` (integer()): Show only the first n items
    - `:"$skip"` (integer()): Skip the first n items
    - `:"$search"` (String.t): Search items by search phrases
    - `:"$filter"` (String.t): Filter items by property values
    - `:"$count"` (boolean()): Include count of items
    - `:"$orderby"` ([String.t]): Order items by property values
    - `:"$select"` ([String.t]): Select properties to be returned
    - `:"$expand"` ([String.t]): Expand related entities

  ### Returns

  - `{:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchemaCollectionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_attribute_mapping_function_schema_list_attribute_mapping_function_schema(Tesla.Env.client, keyword()) :: {:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchemaCollectionResponse.t} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_attribute_mapping_function_schema_list_attribute_mapping_function_schema(connection, opts \\ []) do
    optional_params = %{
      :"$top" => :query,
      :"$skip" => :query,
      :"$search" => :query,
      :"$filter" => :query,
      :"$count" => :query,
      :"$orderby" => :query,
      :"$select" => :query,
      :"$expand" => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/functions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {"2XX", MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchemaCollectionResponse},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end

  @doc """
  Update entity in functions

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `attribute_mapping_function_schema_id` (String.t): The unique identifier of attributeMappingFunctionSchema
  - `microsoft_graph_attribute_mapping_function_schema` (MicrosoftGraphAttributeMappingFunctionSchema): New property values
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_attribute_mapping_function_schema_update_attribute_mapping_function_schema(Tesla.Env.client, String.t, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t, keyword()) :: {:ok, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema.t} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_attribute_mapping_function_schema_update_attribute_mapping_function_schema(connection, attribute_mapping_function_schema_id, microsoft_graph_attribute_mapping_function_schema, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/functions/#{attribute_mapping_function_schema_id}")
      |> add_param(:body, :body, microsoft_graph_attribute_mapping_function_schema)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {"2XX", MicrosoftGraph.Model.MicrosoftGraphAttributeMappingFunctionSchema},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end

  @doc """
  Get the number of the resource

  ### Parameters

  - `connection` (MicrosoftGraph.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"$search"` (String.t): Search items by search phrases
    - `:"$filter"` (String.t): Filter items by property values

  ### Returns

  - `{:ok, integer()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec functions_get_count0c74(Tesla.Env.client, keyword()) :: {:ok, Integer.t} | {:ok, MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError.t} | {:error, Tesla.Env.t}
  def functions_get_count0c74(connection, opts \\ []) do
    optional_params = %{
      :"$search" => :query,
      :"$filter" => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/functions/$count")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {"2XX", false},
      {"4XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError},
      {"5XX", MicrosoftGraph.Model.MicrosoftGraphODataErrorsODataError}
    ])
  end
end
