# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.AccessPackageAssignmentRequestSchedule do
  @moduledoc """
  The range of dates that access is to be assigned to the requestor. This property can't be changed once set.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :expiration,
    :recurrence,
    :startDateTime
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :expiration => MicrosoftGraph.Model.MicrosoftGraphEntitlementManagementScheduleExpiration.t | nil,
    :recurrence => MicrosoftGraph.Model.MicrosoftGraphEntitlementManagementScheduleRecurrence.t | nil,
    :startDateTime => DateTime.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expiration, :struct, MicrosoftGraph.Model.MicrosoftGraphEntitlementManagementScheduleExpiration)
     |> Deserializer.deserialize(:recurrence, :struct, MicrosoftGraph.Model.MicrosoftGraphEntitlementManagementScheduleRecurrence)
     |> Deserializer.deserialize(:startDateTime, :datetime, nil)
  end
end

