# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.ApplicationsApplicationSynchronizationJobsSynchronizationJobProvisionOnDemandRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :parameters
  ]

  @type t :: %__MODULE__{
          :parameters =>
            [
              MicrosoftGraph.Model.ApplicationsApplicationSynchronizationJobsSynchronizationJobProvisionOnDemandRequestParametersInner.t()
            ]
            | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :parameters,
      :list,
      MicrosoftGraph.Model.ApplicationsApplicationSynchronizationJobsSynchronizationJobProvisionOnDemandRequestParametersInner
    )
  end
end
