# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.ApplicationSynchronization do
  @moduledoc """
  Represents the capability for Microsoft Entra identity synchronization through the Microsoft Graph API.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :jobs,
    :secrets,
    :templates
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :id => String.t | nil,
    :jobs => [MicrosoftGraph.Model.MicrosoftGraphSynchronizationJob.t] | nil,
    :secrets => [MicrosoftGraph.Model.ApplicationsApplicationSynchronizationJobsSynchronizationJobValidateCredentialsRequestCredentialsInner.t] | nil,
    :templates => [MicrosoftGraph.Model.MicrosoftGraphSynchronizationTemplate.t] | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:jobs, :list, MicrosoftGraph.Model.MicrosoftGraphSynchronizationJob)
     |> Deserializer.deserialize(:secrets, :list, MicrosoftGraph.Model.ApplicationsApplicationSynchronizationJobsSynchronizationJobValidateCredentialsRequestCredentialsInner)
     |> Deserializer.deserialize(:templates, :list, MicrosoftGraph.Model.MicrosoftGraphSynchronizationTemplate)
  end
end

