# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.AuthenticationFlowsPolicySelfServiceSignUp do
  @moduledoc """
  Contains selfServiceSignUpAuthenticationFlowConfiguration settings that convey whether self-service sign-up is enabled or disabled. Optional. Read-only.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :isEnabled
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :isEnabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

