# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.CallCallRoutesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :final,
    :original,
    :routingType
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :final => MicrosoftGraph.Model.MicrosoftGraphIdentitySet.t | nil,
    :original => MicrosoftGraph.Model.MicrosoftGraphIdentitySet.t | nil,
    :routingType => MicrosoftGraph.Model.MicrosoftGraphRoutingType.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:final, :struct, MicrosoftGraph.Model.MicrosoftGraphIdentitySet)
     |> Deserializer.deserialize(:original, :struct, MicrosoftGraph.Model.MicrosoftGraphIdentitySet)
     |> Deserializer.deserialize(:routingType, :struct, MicrosoftGraph.Model.MicrosoftGraphRoutingType)
  end
end

