# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.CommunicationsCallsCallRedirectRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :callbackUri,
    :targets,
    :timeout
  ]

  @type t :: %__MODULE__{
          :callbackUri => String.t() | nil,
          :targets => [MicrosoftGraph.Model.MicrosoftGraphInvitationParticipantInfo.t()] | nil,
          :timeout => integer() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :targets,
      :list,
      MicrosoftGraph.Model.MicrosoftGraphInvitationParticipantInfo
    )
  end
end
