# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.CommunicationsCallsCallParticipantsParticipantStartHoldMusicRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :clientContext,
    :customPrompt
  ]

  @type t :: %__MODULE__{
          :clientContext => String.t() | nil,
          :customPrompt =>
            MicrosoftGraph.Model.CommunicationsCallsCallRecordResponseRequestPromptsInner.t()
            | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :customPrompt,
      :struct,
      MicrosoftGraph.Model.CommunicationsCallsCallRecordResponseRequestPromptsInner
    )
  end
end
