# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.DelegatedAdminRelationshipCustomer do
  @moduledoc """
  The display name and unique identifier of the customer of the relationship. This is configured either by the partner at the time the relationship is created or by the system after the customer approves the relationship. Can't be changed by the customer.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :displayName,
    :tenantId
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :displayName => String.t | nil,
    :tenantId => String.t | nil
  }

  def decode(value) do
    value
  end
end

