# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.DeviceAppManagementMobileAppsMobileAppMicrosoftGraphAndroidLobAppContentVersionsMobileAppContentFilesMobileAppContentFileCommitRequestFileEncryptionInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :encryptionKey,
    :fileDigest,
    :fileDigestAlgorithm,
    :initializationVector,
    :mac,
    :macKey,
    :profileIdentifier
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :encryptionKey => String.t | nil,
    :fileDigest => String.t | nil,
    :fileDigestAlgorithm => String.t | nil,
    :initializationVector => String.t | nil,
    :mac => String.t | nil,
    :macKey => String.t | nil,
    :profileIdentifier => String.t | nil
  }

  def decode(value) do
    value
  end
end

