# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.DrivesDriveItemsDriveItemPreviewRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :page,
    :zoom
  ]

  @type t :: %__MODULE__{
          :page => String.t() | nil,
          :zoom =>
            MicrosoftGraph.Model.UsersUserFindMeetingTimesRequestMinimumAttendeePercentage.t()
            | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :zoom,
      :struct,
      MicrosoftGraph.Model.UsersUserFindMeetingTimesRequestMinimumAttendeePercentage
    )
  end
end
