# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.EducationAssignmentResourceResource do
  @moduledoc """
  Resource object that has been associated with this assignment.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :createdBy,
    :createdDateTime,
    :displayName,
    :lastModifiedBy,
    :lastModifiedDateTime
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :createdBy => MicrosoftGraph.Model.MicrosoftGraphEducationResourceCreatedBy.t() | nil,
          :createdDateTime => DateTime.t() | nil,
          :displayName => String.t() | nil,
          :lastModifiedBy =>
            MicrosoftGraph.Model.MicrosoftGraphEducationResourceLastModifiedBy.t() | nil,
          :lastModifiedDateTime => DateTime.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :createdBy,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphEducationResourceCreatedBy
    )
    |> Deserializer.deserialize(:createdDateTime, :datetime, nil)
    |> Deserializer.deserialize(
      :lastModifiedBy,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphEducationResourceLastModifiedBy
    )
    |> Deserializer.deserialize(:lastModifiedDateTime, :datetime, nil)
  end
end
