# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.EducationUserPasswordProfile do
  @moduledoc """
  Specifies the password profile for the user. The profile contains the user's password. This property is required when a user is created. The password in the profile must satisfy minimum requirements as specified by the passwordPolicies property. By default, a strong password is required.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :forceChangePasswordNextSignIn,
    :forceChangePasswordNextSignInWithMfa,
    :password
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :forceChangePasswordNextSignIn => boolean() | nil,
    :forceChangePasswordNextSignInWithMfa => boolean() | nil,
    :password => String.t | nil
  }

  def decode(value) do
    value
  end
end

