# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.IdentityB2xUserFlowsB2xIdentityUserFlowUserAttributeAssignmentsSetOrderRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :newAssignmentOrder
  ]

  @type t :: %__MODULE__{
          :newAssignmentOrder =>
            MicrosoftGraph.Model.IdentityB2xUserFlowsB2xIdentityUserFlowUserAttributeAssignmentsGetOrder2XxResponse.t()
            | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :newAssignmentOrder,
      :struct,
      MicrosoftGraph.Model.IdentityB2xUserFlowsB2xIdentityUserFlowUserAttributeAssignmentsGetOrder2XxResponse
    )
  end
end
