# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MeJoinedTeamsTeamMembersAddRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :values
  ]

  @type t :: %__MODULE__{
    :values => [MicrosoftGraph.Model.MeJoinedTeamsTeamMembersAddRequestValuesInner.t] | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:values, :list, MicrosoftGraph.Model.MeJoinedTeamsTeamMembersAddRequestValuesInner)
  end
end

