# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphFolder do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :childCount,
    :view
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :childCount => integer() | nil,
          :view => MicrosoftGraph.Model.MicrosoftGraphFolderView.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:view, :struct, MicrosoftGraph.Model.MicrosoftGraphFolderView)
  end
end
