# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphExpirationPattern do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :duration,
    :endDateTime,
    :type
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :duration => String.t() | nil,
          :endDateTime => DateTime.t() | nil,
          :type => MicrosoftGraph.Model.MicrosoftGraphExpirationPatternType.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:endDateTime, :datetime, nil)
    |> Deserializer.deserialize(
      :type,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphExpirationPatternType
    )
  end
end
