# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphTrainingLanguageDetail do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :content,
    :createdBy,
    :createdDateTime,
    :description,
    :displayName,
    :isDefaultLangauge,
    :lastModifiedBy,
    :lastModifiedDateTime,
    :locale
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :id => String.t | nil,
    :content => String.t | nil,
    :createdBy => MicrosoftGraph.Model.TrainingLanguageDetailCreatedBy.t | nil,
    :createdDateTime => DateTime.t | nil,
    :description => String.t | nil,
    :displayName => String.t | nil,
    :isDefaultLangauge => boolean() | nil,
    :lastModifiedBy => MicrosoftGraph.Model.TrainingLanguageDetailLastModifiedBy.t | nil,
    :lastModifiedDateTime => DateTime.t | nil,
    :locale => String.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:createdBy, :struct, MicrosoftGraph.Model.TrainingLanguageDetailCreatedBy)
     |> Deserializer.deserialize(:createdDateTime, :datetime, nil)
     |> Deserializer.deserialize(:lastModifiedBy, :struct, MicrosoftGraph.Model.TrainingLanguageDetailLastModifiedBy)
     |> Deserializer.deserialize(:lastModifiedDateTime, :datetime, nil)
  end
end

