# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphAssignedTrainingInfo do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :assignedUserCount,
    :completedUserCount,
    :displayName
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :assignedUserCount => integer() | nil,
          :completedUserCount => integer() | nil,
          :displayName => String.t() | nil
        }

  def decode(value) do
    value
  end
end
