# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphMobileAppInstallTimeSettings do
  @moduledoc """
  Contains properties used to determine when to offer an app to devices and when to install the app on devices.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :deadlineDateTime,
    :startDateTime,
    :useLocalTime
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :deadlineDateTime => DateTime.t() | nil,
          :startDateTime => DateTime.t() | nil,
          :useLocalTime => boolean() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:deadlineDateTime, :datetime, nil)
    |> Deserializer.deserialize(:startDateTime, :datetime, nil)
  end
end
