# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphCommentAction do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :isReply,
    :parentAuthor,
    :participants
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :isReply => boolean() | nil,
          :parentAuthor => MicrosoftGraph.Model.MicrosoftGraphCommentActionParentAuthor.t() | nil,
          :participants => [MicrosoftGraph.Model.CaseLastModifiedBy.t()] | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :parentAuthor,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphCommentActionParentAuthor
    )
    |> Deserializer.deserialize(:participants, :list, MicrosoftGraph.Model.CaseLastModifiedBy)
  end
end
