# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphPrinterCapabilitiesCopiesPerJob do
  @moduledoc """
  The range of copies per job supported by the printer.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :end,
    :start
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :end => integer() | nil,
          :start => integer() | nil
        }

  def decode(value) do
    value
  end
end
