# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphWebApplicationImplicitGrantSettings do
  @moduledoc """
  Specifies whether this web application can request tokens using the OAuth 2.0 implicit flow.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :enableAccessTokenIssuance,
    :enableIdTokenIssuance
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :enableAccessTokenIssuance => boolean() | nil,
    :enableIdTokenIssuance => boolean() | nil
  }

  def decode(value) do
    value
  end
end

