# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphInvitation do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :inviteRedeemUrl,
    :inviteRedirectUrl,
    :invitedUser,
    :invitedUserDisplayName,
    :invitedUserEmailAddress,
    :invitedUserMessageInfo,
    :invitedUserType,
    :resetRedemption,
    :sendInvitationMessage,
    :status
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :inviteRedeemUrl => String.t() | nil,
          :inviteRedirectUrl => String.t() | nil,
          :invitedUser => MicrosoftGraph.Model.InvitationInvitedUser.t() | nil,
          :invitedUserDisplayName => String.t() | nil,
          :invitedUserEmailAddress => String.t() | nil,
          :invitedUserMessageInfo =>
            MicrosoftGraph.Model.InvitationInvitedUserMessageInfo.t() | nil,
          :invitedUserType => String.t() | nil,
          :resetRedemption => boolean() | nil,
          :sendInvitationMessage => boolean() | nil,
          :status => String.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:invitedUser, :struct, MicrosoftGraph.Model.InvitationInvitedUser)
    |> Deserializer.deserialize(
      :invitedUserMessageInfo,
      :struct,
      MicrosoftGraph.Model.InvitationInvitedUserMessageInfo
    )
  end
end
