# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphWin32LobAppReturnCode do
  @moduledoc """
  Contains return code properties for a Win32 App
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :returnCode,
    :type
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :returnCode => integer() | nil,
          :type => MicrosoftGraph.Model.MicrosoftGraphWin32LobAppReturnCodeType.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :type,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphWin32LobAppReturnCodeType
    )
  end
end
