# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphInformationProtection do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :bitlocker,
    :threatAssessmentRequests
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :bitlocker => MicrosoftGraph.Model.MicrosoftGraphInformationProtectionBitlocker.t | nil,
    :threatAssessmentRequests => [MicrosoftGraph.Model.MicrosoftGraphThreatAssessmentRequest.t] | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bitlocker, :struct, MicrosoftGraph.Model.MicrosoftGraphInformationProtectionBitlocker)
     |> Deserializer.deserialize(:threatAssessmentRequests, :list, MicrosoftGraph.Model.MicrosoftGraphThreatAssessmentRequest)
  end
end

