# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphTargetedManagedAppGroupType do
  @moduledoc """
  Indicates a collection of apps to target which can be one of several pre-defined lists of apps or a manually selected list of apps
  """

  @derive Jason.Encoder
  defstruct []

  @type t :: %__MODULE__{}

  def decode(value) do
    value
  end
end
