# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphAttributeMappingSource do
  @moduledoc """
  Defines how a value should be extracted (or transformed) from the source object.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :expression,
    :name,
    :parameters,
    :type
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :expression => String.t | nil,
    :name => String.t | nil,
    :parameters => [MicrosoftGraph.Model.MicrosoftGraphAttributeMappingSourceParametersInner.t] | nil,
    :type => MicrosoftGraph.Model.MicrosoftGraphAttributeMappingSourceType.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:parameters, :list, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingSourceParametersInner)
     |> Deserializer.deserialize(:type, :struct, MicrosoftGraph.Model.MicrosoftGraphAttributeMappingSourceType)
  end
end

