# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphAdminConsentRequestPolicy do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :isEnabled,
    :notifyReviewers,
    :remindersEnabled,
    :requestDurationInDays,
    :reviewers,
    :version
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :isEnabled => boolean() | nil,
          :notifyReviewers => boolean() | nil,
          :remindersEnabled => boolean() | nil,
          :requestDurationInDays => integer() | nil,
          :reviewers =>
            [MicrosoftGraph.Model.AccessReviewScheduleDefinitionFallbackReviewersInner.t()] | nil,
          :version => integer() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :reviewers,
      :list,
      MicrosoftGraph.Model.AccessReviewScheduleDefinitionFallbackReviewersInner
    )
  end
end
