# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphResourceSpecificPermission do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :description,
    :displayName,
    :id,
    :isEnabled,
    :value
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :description => String.t | nil,
    :displayName => String.t | nil,
    :id => String.t | nil,
    :isEnabled => boolean() | nil,
    :value => String.t | nil
  }

  def decode(value) do
    value
  end
end

