# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphSecurityHostCookie do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :domain,
    :firstSeenDateTime,
    :host,
    :lastSeenDateTime,
    :name
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :domain => String.t() | nil,
          :firstSeenDateTime => DateTime.t() | nil,
          :host => MicrosoftGraph.Model.MicrosoftGraphSecurityHost.t() | nil,
          :lastSeenDateTime => DateTime.t() | nil,
          :name => String.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:firstSeenDateTime, :datetime, nil)
    |> Deserializer.deserialize(:host, :struct, MicrosoftGraph.Model.MicrosoftGraphSecurityHost)
    |> Deserializer.deserialize(:lastSeenDateTime, :datetime, nil)
  end
end
