# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphAccessPackageResource do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :createdDateTime,
    :description,
    :displayName,
    :environment,
    :modifiedDateTime,
    :originId,
    :originSystem,
    :roles,
    :scopes
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :createdDateTime => DateTime.t() | nil,
          :description => String.t() | nil,
          :displayName => String.t() | nil,
          :environment => MicrosoftGraph.Model.AccessPackageResourceEnvironment.t() | nil,
          :modifiedDateTime => DateTime.t() | nil,
          :originId => String.t() | nil,
          :originSystem => String.t() | nil,
          :roles => [MicrosoftGraph.Model.MicrosoftGraphAccessPackageResourceRole.t()] | nil,
          :scopes => [MicrosoftGraph.Model.MicrosoftGraphAccessPackageResourceScope.t()] | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:createdDateTime, :datetime, nil)
    |> Deserializer.deserialize(
      :environment,
      :struct,
      MicrosoftGraph.Model.AccessPackageResourceEnvironment
    )
    |> Deserializer.deserialize(:modifiedDateTime, :datetime, nil)
    |> Deserializer.deserialize(
      :roles,
      :list,
      MicrosoftGraph.Model.MicrosoftGraphAccessPackageResourceRole
    )
    |> Deserializer.deserialize(
      :scopes,
      :list,
      MicrosoftGraph.Model.MicrosoftGraphAccessPackageResourceScope
    )
  end
end
