# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphPlannerExternalReference do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :alias,
    :lastModifiedBy,
    :lastModifiedDateTime,
    :previewPriority,
    :type
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :alias => String.t() | nil,
          :lastModifiedBy =>
            MicrosoftGraph.Model.MicrosoftGraphPlannerExternalReferenceLastModifiedBy.t() | nil,
          :lastModifiedDateTime => DateTime.t() | nil,
          :previewPriority => String.t() | nil,
          :type => String.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :lastModifiedBy,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphPlannerExternalReferenceLastModifiedBy
    )
    |> Deserializer.deserialize(:lastModifiedDateTime, :datetime, nil)
  end
end
