# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphAuthenticationMethodFeatureConfigurationIncludeTarget do
  @moduledoc """
  A single entity that is included in this feature.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :targetType
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :id => String.t | nil,
    :targetType => MicrosoftGraph.Model.MicrosoftGraphFeatureTargetTargetType.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:targetType, :struct, MicrosoftGraph.Model.MicrosoftGraphFeatureTargetTargetType)
  end
end

