# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphShared do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :owner,
    :scope,
    :sharedBy,
    :sharedDateTime
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :owner => MicrosoftGraph.Model.MicrosoftGraphSharedOwner.t() | nil,
          :scope => String.t() | nil,
          :sharedBy => MicrosoftGraph.Model.MicrosoftGraphSharedSharedBy.t() | nil,
          :sharedDateTime => DateTime.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:owner, :struct, MicrosoftGraph.Model.MicrosoftGraphSharedOwner)
    |> Deserializer.deserialize(
      :sharedBy,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphSharedSharedBy
    )
    |> Deserializer.deserialize(:sharedDateTime, :datetime, nil)
  end
end
