# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphUserExperienceAnalyticsSettings do
  @moduledoc """
  The user experience analytics insight is the recomendation to improve the user experience analytics score.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :configurationManagerDataConnectorConfigured
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :configurationManagerDataConnectorConfigured => boolean() | nil
  }

  def decode(value) do
    value
  end
end

