# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphEducationSchool do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :description,
    :displayName,
    :externalSource,
    :externalSourceDetail,
    :address,
    :administrativeUnit,
    :classes,
    :createdBy,
    :externalId,
    :externalPrincipalId,
    :fax,
    :highestGrade,
    :lowestGrade,
    :phone,
    :principalEmail,
    :principalName,
    :schoolNumber,
    :users
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :id => String.t | nil,
    :description => String.t | nil,
    :displayName => String.t | nil,
    :externalSource => MicrosoftGraph.Model.EducationOrganizationExternalSource.t | nil,
    :externalSourceDetail => String.t | nil,
    :address => MicrosoftGraph.Model.EducationSchoolAddress.t | nil,
    :administrativeUnit => MicrosoftGraph.Model.EducationSchoolAdministrativeUnit.t | nil,
    :classes => [MicrosoftGraph.Model.MicrosoftGraphEducationClass.t] | nil,
    :createdBy => MicrosoftGraph.Model.EducationSchoolCreatedBy.t | nil,
    :externalId => String.t | nil,
    :externalPrincipalId => String.t | nil,
    :fax => String.t | nil,
    :highestGrade => String.t | nil,
    :lowestGrade => String.t | nil,
    :phone => String.t | nil,
    :principalEmail => String.t | nil,
    :principalName => String.t | nil,
    :schoolNumber => String.t | nil,
    :users => [MicrosoftGraph.Model.MicrosoftGraphEducationUser.t] | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:externalSource, :struct, MicrosoftGraph.Model.EducationOrganizationExternalSource)
     |> Deserializer.deserialize(:address, :struct, MicrosoftGraph.Model.EducationSchoolAddress)
     |> Deserializer.deserialize(:administrativeUnit, :struct, MicrosoftGraph.Model.EducationSchoolAdministrativeUnit)
     |> Deserializer.deserialize(:classes, :list, MicrosoftGraph.Model.MicrosoftGraphEducationClass)
     |> Deserializer.deserialize(:createdBy, :struct, MicrosoftGraph.Model.EducationSchoolCreatedBy)
     |> Deserializer.deserialize(:users, :list, MicrosoftGraph.Model.MicrosoftGraphEducationUser)
  end
end

