# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.MicrosoftGraphOAuthConsentAppDetail do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :appScope,
    :displayLogo,
    :displayName
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :appScope => MicrosoftGraph.Model.MicrosoftGraphOAuthConsentAppDetailAppScope.t() | nil,
          :displayLogo => String.t() | nil,
          :displayName => String.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :appScope,
      :struct,
      MicrosoftGraph.Model.MicrosoftGraphOAuthConsentAppDetailAppScope
    )
  end
end
