# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.PlannerTaskPreviewType do
  @moduledoc """
  This sets the type of preview that shows up on the task. The possible values are: automatic, noPreview, checklist, description, reference.
  """

  @derive Jason.Encoder
  defstruct []

  @type t :: %__MODULE__{}

  def decode(value) do
    value
  end
end
