# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.TeamsAppInstallationTeamsAppDefinition do
  @moduledoc """
  The details of this version of the app.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :authorization,
    :bot,
    :createdBy,
    :description,
    :displayName,
    :lastModifiedDateTime,
    :publishingState,
    :shortDescription,
    :teamsAppId,
    :version
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :authorization => MicrosoftGraph.Model.TeamsAppDefinitionAuthorization.t() | nil,
          :bot => MicrosoftGraph.Model.TeamsAppDefinitionBot.t() | nil,
          :createdBy => MicrosoftGraph.Model.CaseLastModifiedBy.t() | nil,
          :description => String.t() | nil,
          :displayName => String.t() | nil,
          :lastModifiedDateTime => DateTime.t() | nil,
          :publishingState => MicrosoftGraph.Model.TeamsAppDefinitionPublishingState.t() | nil,
          :shortDescription => String.t() | nil,
          :teamsAppId => String.t() | nil,
          :version => String.t() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :authorization,
      :struct,
      MicrosoftGraph.Model.TeamsAppDefinitionAuthorization
    )
    |> Deserializer.deserialize(:bot, :struct, MicrosoftGraph.Model.TeamsAppDefinitionBot)
    |> Deserializer.deserialize(:createdBy, :struct, MicrosoftGraph.Model.CaseLastModifiedBy)
    |> Deserializer.deserialize(:lastModifiedDateTime, :datetime, nil)
    |> Deserializer.deserialize(
      :publishingState,
      :struct,
      MicrosoftGraph.Model.TeamsAppDefinitionPublishingState
    )
  end
end
