# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.TeamworkTeamsAppSettings do
  @moduledoc """
  Represents tenant-wide settings for all Teams apps in the tenant.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :allowUserRequestsForAppAccess
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :allowUserRequestsForAppAccess => boolean() | nil
        }

  def decode(value) do
    value
  end
end
