# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.Win32LobAppMsiInformation do
  @moduledoc """
  The MSI details if this Win32 app is an MSI app.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :packageType,
    :productCode,
    :productName,
    :productVersion,
    :publisher,
    :requiresReboot,
    :upgradeCode
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :packageType => MicrosoftGraph.Model.MicrosoftGraphWin32LobAppMsiPackageType.t | nil,
    :productCode => String.t | nil,
    :productName => String.t | nil,
    :productVersion => String.t | nil,
    :publisher => String.t | nil,
    :requiresReboot => boolean() | nil,
    :upgradeCode => String.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:packageType, :struct, MicrosoftGraph.Model.MicrosoftGraphWin32LobAppMsiPackageType)
  end
end

