# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.WindowsInformationProtectionDataRecoveryCertificate do
  @moduledoc """
  Specifies a recovery certificate that can be used for data recovery of encrypted files. This is the same as the data recovery agent(DRA) certificate for encrypting file system(EFS)
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :certificate,
    :description,
    :expirationDateTime,
    :subjectName
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :certificate => String.t | nil,
    :description => String.t | nil,
    :expirationDateTime => DateTime.t | nil,
    :subjectName => String.t | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expirationDateTime, :datetime, nil)
  end
end

