# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.WorkbookChartAxisMajorGridlines do
  @moduledoc """
  Returns a gridlines object that represents the major gridlines for the specified axis. Read-only.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :format,
    :visible
  ]

  @type t :: %__MODULE__{
    :"@odata.type" => String.t,
    :id => String.t | nil,
    :format => MicrosoftGraph.Model.WorkbookChartGridlinesFormat.t | nil,
    :visible => boolean() | nil
  }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:format, :struct, MicrosoftGraph.Model.WorkbookChartGridlinesFormat)
  end
end

