# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MicrosoftGraph.Model.WorkbookChartTitle do
  @moduledoc """
  Represents the title of the specified chart, including the text, visibility, position and formating of the title. Read-only.
  """

  @derive Jason.Encoder
  defstruct [
    :"@odata.type",
    :id,
    :format,
    :overlay,
    :text,
    :visible
  ]

  @type t :: %__MODULE__{
          :"@odata.type" => String.t(),
          :id => String.t() | nil,
          :format => MicrosoftGraph.Model.WorkbookChartTitleFormat.t() | nil,
          :overlay => boolean() | nil,
          :text => String.t() | nil,
          :visible => boolean() | nil
        }

  alias MicrosoftGraph.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:format, :struct, MicrosoftGraph.Model.WorkbookChartTitleFormat)
  end
end
